name = "lince"
prefix = "lince"
author = "Lince Team"

[files]
include = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "docs/README_*.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_lince_ca.paa",
    "meta.cpp",
]

[version]
git_hash = 0

[properties]
version = "{{git \"id 8\"}}"

[asc]
enabled = true
exclude = [
    "/initsettings.sqf",
    "/initkeybinds.sqf",
    "/xeh_prep.sqf",
]