name: CI

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Lint (sqflint)
      uses: arma-actions/sqflint@master
      continue-on-error: true # No failure due to many false-positives
  hemtt:
    name: Build with HEMTT
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build with HEMTT
      uses: gruppe-adler/action-release-with-hemtt@2.2.0
      id: build
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.build.outputs.zip_name }}
        path: ${{ steps.build.outputs.release_path }}