
name: 'RELEASE'

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  upload-to-gh:
    name: Upload to GitHub release
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Release with HEMTT - MultiTheFranky
      uses: MultiTheFranky/action-release-with-hemtt@0.0.5
      id: build
    - name: Upload asset
      uses: shogo82148/actions-upload-release-asset@v1
      with: 
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.build.outputs.zip_path }}
        asset_content_type: application/zip